### ISSUE TITLE
As the director, I want to see the overall workflow so that I can understand and explain it

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/cloud-tvnews#6]
### Feature
State machines written in Amazon State Language (ASL) can be visualized with each step as a unit in a flowchart.  When the state machines trigger lambdas or other task states, their status is displayed visually.  Initially using a pass state for a state machine instead of a task state would allow the whole workflow to be defined, with tasks added to the workflow as they are completed.  The workflow can be modified as necessary by adding, removing, or changing the connections between the state machines.

- [x] Determine the major tasks to be completed in the overall process.
- [x] Create an appropriate IAM role for the state machine
- [x] Create CloudWatch and CloudTrail S3 bucket triggers to start the machine
- [x] Create steps for each task.
- [x] Assign type: Pass to each step.
- [x] Create the connections between the steps.

### Errors
~Perform an execution and examine step details to ensure that the steps flow as envisioned.~

### Reporting
No report is necessary given that the machine can be visualized in the Step Function AWS console.

**Comment by baskaufs** [comment]
Hey @jimdur8n, here's a very rough overview of major tasks in the system -- probably with the wrong names for everything and many missing things.  If you can comment on major additions or corrections, I'll then try to start building the rough state machine.

Major Tasks:
- incoming data is from Snapstream, drops into S3 bucket
- periodically, new data comes in to change the MediaConvert settings, but that's probably a different machine because it's not triggered by the incoming data from Snapstream. It feeds into the main system as the JSON file that goes into MediaConvert
- GIF and reduced resolution video stored in viewing system
- highres video stored in Glacier
- processing of SRT output from snapstream to prepare for segmentation, probably output as JSON
- ~wait function waits for input from segmentation (human or machine)~
- processed SRT JSON combined with segmentation data to produce rough transcript data
- rough transcript data goes to tagging/concepting (Comprehend or Yewno), also to Mechanical Turks for cleanup, and storage in database
- (this may be the end of the main machine, since separate machines might get triggered to start when the tags/concepts come back, or when the transcript data come back from human cleanup)
- Cleaned up transcript data replaces previously stored rough transcript data in database
- somewhere in here transcript data reunites with GIF, reduced res video, and indexing data (tags/concepts/keywords) in the end user's system/website/API
- data packaged somehow for transfer to partner institutions

This doesn't have to be perfect, just enough for me to start putting the machine pieces together.  We can change and edit the machine(s) later.

**Comment by jimdur8n** [comment]
Hi Steve, this is a good summary. I have just a few clarifications:

HiRes vids are (ideally) stored on ACCRE/LSTORE then mirrored to Glacier or Oracle Cloud Storage.
GIF creation should happen after the time-codes are submitted so they represent only the segment.
I think the mechanism for inputing the time-coded data should be versatile and handle either manual or auto input.

**Comment by baskaufs** [comment]
@CliffordAnderson @jimdur8n I'm ready to start building the state function scaffolding and decided that it would probably be best to create a separate user for that so we don't need to use our personal credentials with it.  I set up a new user in the TV news account called "stateMachineUser".  I added it to the LambdaScripts group (which didn't have any members thus far).  I changed the permissions on the LambdaScripts group to AdministratorAccess.  I realize that isn't optimal, but every time I've tried to do any work on AWS, I have been hampered with stuff not working unless I had administrator access and I'm planning to do most of the work on this project as the stateMachineUser.  

I created a group in KeyBase for this project and added you as members.  The credentials for this new user are there if you need to access them.

**Comment by baskaufs** [comment]
Wait state only waits for a fixed time interval or until a stated time, not for completion of an action.  So in a situation where we are waiting for input from a human, there should be a separate state machine that is triggered by another S3 bucket drop or other CloudWatch event.

**Comment by baskaufs** [comment]
Completed with merge of #11.  Didn't actually make any data flow through the system (last unchecked checkbox) but I don't really care about that at this point.
