### ISSUE TITLE
As a development team member, I want to refer to a workflow document so I don't forget steps saving my work

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/cloud-tvnews#7]
Develop workflow documentation for effectively developing code, loading it to AWS, and archiving it in GitHub

- [x] Quickstart documentation for installing AWS command line interface (CLI) on local computer.
- [x] Create a list of potentially reusable IAM ARNs for commonly used permissions roles
- [x] Notes on zipping lambda packages with template CLI command for loading the lambda
- [x] Create logical structure in repo for storing lambdas, test JSON input, state machine code, etc.
~Decide whether versioning of lambdas is necessary. If so, decide on naming conventions  and create a record system for the versions and their ARNs (if GitHub doesn't do this well enough on its own). (moved this to #16)~

**Comment by baskaufs** [comment]
I found notes on zipping Python modules with the scripts [here](https://github.com/HeardLibrary/tvnews-data-scripts/tree/master/scripts/lambda/testHttp).

**Comment by baskaufs** [comment]
Removed remaining checkbox to a separate issue.

**Comment by jimdur8n** [comment]
@baskaufs the System 1 workflow looks great. Thanks Steve!
