### ISSUE TITLE
Do we have to use the Wiki?

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/cloud-tvnews#8]
@CliffordAnderson do we need to document the code in the Wiki?  I've never seen the benefit over just putting markdown pages in the appropriate places in the repo.  I suppose if we eventually come up with some kind of user manual, the wiki might be nice.  But I like to see the documentation for code in the same place as the code (i.e. README.md in the directory with the code).

**Comment by CliffordAnderson** [comment]
@baskaufs I think it would be useful to have both in place. We need a higher-level overview for staff members (and future users) to read. But don't worry about putting documentation there for now if you are describing your contributions with markdown in the appropriate locations.

**Comment by baskaufs** [comment]
Cool
